# Generated by Django 2.0.6 on 2019-05-03 06:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockkeeping', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gst_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('gstin_vendor', models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True)),
                ('gstin_self', models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('ugst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('total_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('withinstate', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_gstinput', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchasegst', to='stockkeeping.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Gst_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('gstin_vendor', models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True)),
                ('gstin_self', models.CharField(default='19ABCDE1234F2Z5', max_length=100, null=True, unique=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('ugst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('withinstate', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_gstoutput', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesgst', to='stockkeeping.Sales')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_gst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('hsn', models.PositiveIntegerField()),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_stockgst', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockgst', to='stockkeeping.Stockdata')),
            ],
        ),
    ]
