# Generated by Django 2.0.6 on 2019-09-09 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField()),
                ('voucher_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('ATM', 'ATM'), ('Cash', 'Cash'), ('Cheque/DD', 'Cheque/DD'), ('Card', 'Card'), ('ECS', 'ECS'), ('Electronic Cheque', 'Electronic Cheque'), ('Electronic DD/PO', 'Electronic DD/PO'), ('e-Fund Transfer', 'e-Fund Transfer'), ('Others', 'Others')], default='Cheque/DD', max_length=60)),
                ('instrument_no', models.CharField(blank=True, max_length=50)),
                ('bank_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContraVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContraVoucherRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_type', models.CharField(default='Journal', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('narration', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True)),
                ('url_hash', models.CharField(blank=True, max_length=100)),
                ('ledger_name', models.CharField(max_length=80)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('balance_opening', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('party_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('pan_no', models.CharField(blank=True, max_length=10)),
                ('gst_no', models.CharField(blank=True, max_length=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('duty_tax_type', models.CharField(blank=True, choices=[('Others', 'Others'), ('GST', 'GST')], default='Others', max_length=10)),
                ('tax_type', models.CharField(blank=True, choices=[('Central Tax', 'Central Tax'), ('Cess', 'Cess'), ('Integrated Tax', 'Integrated Tax'), ('State Tax', 'State Tax')], max_length=100)),
                ('assessable_value', models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('GST', 'GST')], default='Not Applicable', max_length=20)),
                ('appropiate_to', models.CharField(blank=True, choices=[('Both', 'Both'), ('Goods', 'Goods'), ('Services', 'Services')], default='Both', max_length=20)),
                ('calculation_method', models.CharField(blank=True, choices=[('Based on Quantity', 'Based on Quantity'), ('Based on Value', 'Based on Value')], default='Based on Value', max_length=20)),
                ('gst_applicable', models.CharField(blank=True, choices=[('Applicable', 'Applicable'), ('Not Applicable', 'Not Applicable'), ('Undefined', 'Undefined')], default='Not Applicable', max_length=20)),
                ('set_or_alter_gst', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('set_or_alter_gst_tax', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('supply_type', models.CharField(blank=True, choices=[('Goods', 'Goods'), ('Services', 'Services')], default='Goods', max_length=10)),
                ('registration_type', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Composition', 'Composition'), ('Consumer', 'Consumer'), ('Regular', 'Regular'), ('Unregistered', 'Unregistered')], default='Unregistered', max_length=20)),
                ('is_eoperator', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('deemed_expoter', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('party_type', models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Deemed Export', 'Deemed Export'), ('Embassy/UN Body', 'Embassy/UN Body'), ('SEZ', 'SEZ')], default='Not Applicable', max_length=100)),
                ('is_transporter', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('transporter_id', models.CharField(blank=True, max_length=50)),
                ('hsn_desc', models.CharField(blank=True, max_length=255)),
                ('hsn_no', models.CharField(blank=True, max_length=20)),
                ('is_non_gst', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('nature_transactions_purchase', models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Branch Transfer Inward', 'Branch Transfer Inward'), ('Imports Exempt', 'Imports Exempt'), ('Imports Nil Rated', 'Imports Nil Rated'), ('Imports Taxable', 'Imports Taxable'), ('Interstate Purchase Exempt', 'Interstate Purchase Exempt'), ('Interstate Purchase from Unregistered Dealer - Exempt', 'Interstate Purchase from Unregistered Dealer - Exempt'), ('Interstate Purchase from Unregistered Dealer - Nil Rated', 'Interstate Purchase from Unregistered Dealer - Nil Rated'), ('Interstate Purchase from Unregistered Dealer - Services', 'Interstate Purchase from Unregistered Dealer - Services'), ('Interstate Purchase from Unregistered Dealer - Taxable', 'Interstate Purchase from Unregistered Dealer - Taxable'), ('Interstate Purchase - Nil Rated', 'Interstate Purchase  - Nil Rated '), ('Interstate Purchase - Taxable', 'Interstate Purchase  - Taxable'), ('Interstate Purchase Deemed Exports - Exempt', 'Interstate Purchase Deemed Exports - Exempt'), ('Interstate Purchase Deemed Exports - Nil Rated', 'Interstate Purchase Deemed Exports - Nil Rated'), ('Interstate Purchase Deemed Exports - Taxable', 'Interstate Purchase Deemed Exports - Taxable'), ('Purchase Deemed Exports - Exempt', 'Purchase Deemed Exports - Exempt'), ('Purchase Deemed Exports - Nil Rated', 'Purchase Deemed Exports - Nil Rated'), ('Purchase Deemed Exports - Taxable', 'Purchase Deemed Exports - Taxable'), ('Purchase Exempt', 'Purchase Exempt'), ('Purchase From Composition Dealer', 'Purchase From Composition Dealer'), ('Purchase From SEZ - Exempt', 'Purchase From SEZ - Exempt'), ('Purchase From SEZ - LUT/Bond', 'Purchase From SEZ - LUT/Bond'), ('Purchase From SEZ - Nil Rated ', 'Purchase From SEZ - Nil Rated'), ('Purchase From SEZ - Taxable', 'Purchase From SEZ - Taxable'), ('Purchase From SEZ (Without Bill Of Entry) - Exempt', 'Purchase From SEZ (Without Bill Of Entry) - Exempt'), ('Purchase From SEZ (Without Bill Of Entry) - Nil Rated', 'Purchase From SEZ (Without Bill Of Entry) - Nil Rated'), ('Purchase From SEZ (Without Bill Of Entry) - Taxable', 'Purchase From SEZ (Without Bill Of Entry) - Taxable'), ('Purchase From Unregister Dealer - Exempt', 'Purchase From Unregister Dealer - Exempt'), ('Purchase From Unregister Dealer - Nil Rated', 'Purchase From Unregister Dealer - Nil Rated'), ('Purchase From Unregister Dealer - Taxable', 'Purchase From Unregister Dealer - Taxable'), ('Purchase Nil Rated', 'Purchase Nil Rated'), ('Intrastate Purchase Taxable', 'Intrastate Purchase Taxable')], default='Not Applicable', max_length=100)),
                ('nature_transactions_sales', models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Branch Transfer outward', 'Branch Transfer outward'), ('Deemed Exports Exempt', 'Deemed Exports Exempt'), ('Deemed Exports Nil Rated', 'Deemed Exports Nil Rated'), ('Deemed Exports Taxable', 'Deemed Exports Taxable'), ('Exports Exempt', 'Exports Exempt'), ('Exports LUT/Bond', 'Exports LUT/Bond'), ('Exports Nil Rated', 'Exports Nil Rated'), ('Exports Taxable', 'Exports Taxable'), ('Interstate Sales Exempt', 'Interstate Sales Exempt'), ('Interstate Sales Nil Rated', 'Interstate Sales Nil Rated '), ('Interstate Sales - Taxable', 'Interstate Sales   - Taxable'), ('Interstate Sales to Embassy / UN Body- Exempt', 'Interstate Sales to Embassy / UN Body- Exempt'), ('Interstate Sales to Embassy / UN Body- Nil Rated', 'Interstate Sales to Embassy / UN Body- Nil Rated'), ('Interstate Sales to Embassy / UN Body- Taxable', 'Interstate Sales to Embassy / UN Body- Taxable'), ('Intrastate Deemed Exports Exempt', 'Intrastate Deemed Exports Exempt'), ('Intrastate Deemed Exports Nil Rated', 'Intrastate Deemed Exports Nil Rated'), ('Intrastate Deemed Exports Taxable', 'Intrastate Deemed Exports Taxable'), ('Sales Exempt', 'Sales Exempt'), ('Sales Nil Rated', 'Sales Nil Rated'), ('Intrastate Sales Taxable', 'Intrastate Sales Taxable'), ('Sales to Consumer - Exempt', 'Sales to Consumer - Exempt'), ('Sales to Consumer - Nil Rated ', 'Sales to Consumer - Nil Rated'), ('Sales to Consumer - Taxable', 'Sales to Consumer - Taxable'), ('Sales to SEZ - Exempt', 'Sales to SEZ - Exempt'), ('Sales to SEZ - LUT/Bond', 'Sales to SEZ - LUT/Bond'), ('Sales to SEZ - Nil Rated', 'Sales to SEZ - Nil Rated'), ('Sales to SEZ - Taxable', 'Sales to SEZ - Taxable')], default='Not Applicable', max_length=100)),
                ('goods_nature', models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Capital Goods', 'Capital Goods')], default='Not Applicable', max_length=20)),
                ('taxability', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Exempt', 'Exempt'), ('Nil Rated', 'Nil Rated'), ('Taxable', 'Taxable')], default='Unknown', max_length=20)),
                ('integrated_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20)),
                ('central_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20)),
                ('state_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20)),
                ('cess', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20)),
                ('assessee_of_other_teritory', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
            ],
            options={
                'ordering': ['ledger_name'],
            },
        ),
        migrations.CreateModel(
            name='MultiJournalVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('narration', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiJournalVoucherCrRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MultiJournalVoucherDrRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucherRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_receipt_voucher', to='accounting_entry.LedgerMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_receipt_voucher_row', to='accounting_entry.LedgerMaster')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_receipt_voucher_row', to='accounting_entry.ReceiptVoucher')),
            ],
        ),
    ]
