# Generated by Django 2.0.6 on 2019-08-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_entry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bracketline', '0002_initial_data'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_receipt_voucher', to='company.Company'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receipt_voucher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodselected',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvoucherrows',
            name='particular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_paryment_voucher_row', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='paymentvoucherrows',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payment_voucher_row', to='accounting_entry.PaymentVoucher'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_payment_voucher', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_voucher', to='company.Company'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_voucher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multijournalvoucherdrrows',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_multi_journal_voucher_dr_rows', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='multijournalvoucherdrrows',
            name='multi_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_journal_voucher_dr_rows', to='accounting_entry.MultiJournalVoucher'),
        ),
        migrations.AddField(
            model_name='multijournalvouchercrrows',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_multi_journal_voucher_cr_rows', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='multijournalvouchercrrows',
            name='multi_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_journal_voucher_cr_rows', to='accounting_entry.MultiJournalVoucher'),
        ),
        migrations.AddField(
            model_name='multijournalvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_multi_journal_voucher', to='company.Company'),
        ),
        migrations.AddField(
            model_name='multijournalvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_multi_journal_voucher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgermaster',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ledger_master', to='company.Company'),
        ),
        migrations.AddField(
            model_name='ledgermaster',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_master_country', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='ledgermaster',
            name='ledger_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_ledger', to='accounting_entry.LedgerGroup'),
        ),
        migrations.AddField(
            model_name='ledgermaster',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_master_state', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='ledgermaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ledger_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ledger_group', to='company.Company'),
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='group_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bracketline.GroupBase'),
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='self_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='master_group', to='accounting_entry.LedgerGroup'),
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ledger_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_journal_voucher', to='company.Company'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='cr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cr_ledger_journal_voucher', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='dr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dr_ledger_journal_voucher', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_journal_voucher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contravoucherrows',
            name='contra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contra_contra_voucher_row', to='accounting_entry.ContraVoucher'),
        ),
        migrations.AddField(
            model_name='contravoucherrows',
            name='particular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_contra_voucher_row', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ledger_contra_voucher', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contra_voucher', to='company.Company'),
        ),
        migrations.AddField(
            model_name='contravoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contra_voucher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_reconciliation', to='company.Company'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='cr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cr_ledger_bank_reconciliation', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='dr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dr_ledger_bank_reconciliation', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_reconcliation', to=settings.AUTH_USER_MODEL),
        ),
    ]
