# Generated by Django 2.0.6 on 2019-08-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('accounting_entry', '0002_auto_20190814_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgergroup',
            options={'ordering': ['group_name']},
        ),
        migrations.AlterUniqueTogether(
            name='ledgergroup',
            unique_together={('company', 'group_name')},
        ),
        migrations.AlterUniqueTogether(
            name='ledgermaster',
            unique_together={('company', 'ledger_name')},
        ),
    ]
