# Generated by Django 2.0.6 on 2019-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0005_auto_20190822_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgermaster',
            name='central_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ledgermaster',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ledgermaster',
            name='integrated_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ledgermaster',
            name='state_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
