# Generated by Django 2.0.6 on 2019-08-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import income_tax_compute.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_year', models.CharField(choices=[('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020')], default=income_tax_compute.models.get_default_assesment_year, max_length=9)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_allowence', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_taxable_perqisite', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_deduction_us16', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_prof_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_entmnt_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('salary_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('house_property_net_adjusted', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('house_property_deduction_us24', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('house_property_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit_gain_net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit_gain_income_not_allowable', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit_gain_expense_not_allowable', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit_gain_income_exempt', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit_gain_income_skiped', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('profit_gain_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('capital_gain_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('capital_gain_exempt', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('capital_gain_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('other_income_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('other_income_deduction_us57', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('other_income_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_income_1_2_3_4_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('adjustment_setoff_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('gross_total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('deduction_80c_80u', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('net_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tax_on_net_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('rebate', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tax_and_surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('education_cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tds', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('advance_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('self_assessment_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('prepaid_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tax_liability_refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_company', to='company.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
