# Generated by Django 2.0.6 on 2019-08-14 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracketline', '0002_initial_data'),
        ('stock_keeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotevoucher',
            name='despatch_info',
            field=models.CharField(blank=True, max_length=132),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='despatch_no',
            field=models.CharField(blank=True, max_length=132),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='destination',
            field=models.CharField(blank=True, max_length=132),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='discharge_port',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='flight_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='landing_bill',
            field=models.CharField(blank=True, max_length=132),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='landing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='loading_port',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='shipper_place',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='supply_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_note_supply_country', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='vechicle_no',
            field=models.CharField(blank=True, max_length=132),
        ),
        migrations.AlterField(
            model_name='creditnotestock',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creditnotevoucher',
            name='bill_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
