# Generated by Django 2.0.6 on 2019-08-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_keeping', '0002_auto_20190814_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='nature_transactions_purchase',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Branch Transfer Inward', 'Branch Transfer Inward'), ('Imports Exempt', 'Imports Exempt'), ('Imports Nil Rated', 'Imports Nil Rated'), ('Imports Taxable', 'Imports Taxable'), ('Interstate Purchase exempt', 'Interstate Purchase exempt'), ('Interstate Purchase from Unregistered Dealer - Exempt', 'Interstate Purchase from Unregistered Dealer - Exempt'), ('Interstate Purchase from Unregistered Dealer - Nil Rated', 'Interstate Purchase from Unregistered Dealer - Nil Rated'), ('Interstate Purchase from Unregistered Dealer - Services', 'Interstate Purchase from Unregistered Dealer - Services'), ('Interstate Purchase from Unregistered Dealer - Taxable', 'Interstate Purchase from Unregistered Dealer - Taxable'), ('Interstate Purchase - Nil Rated', 'Interstate Purchase  - Nil Rated '), ('Interstate Purchase - Taxable', 'Interstate Purchase  - Taxable'), ('Intrastate Purchase Deemed Exports - Exempt', 'Intrastate Purchase Deemed Exports - Exempt'), ('Intrastate Purchase Deemed Exports - Nil Rated', 'Intrastate Purchase Deemed Exports - Nil Rated'), ('Intrastate Purchase Deemed Exports - Taxable', 'Intrastate Purchase Deemed Exports - Taxable'), ('Purchase Deemed Exports - Exempt', 'Purchase Deemed Exports - Exempt'), ('Purchase Deemed Exports - Nil Rated', 'Purchase Deemed Exports - Nil Rated'), ('Purchase Deemed Exports - Taxable', 'Purchase Deemed Exports - Taxable'), ('Purchase Exempt', 'Purchase Exempt'), ('Purchase From Composition Dealer', 'Purchase From Composition Dealer'), ('Purchase From SEZ - Exempt', 'Purchase From SEZ - Exempt'), ('Purchase From SEZ - LUT/Bond', 'Purchase From SEZ - LUT/Bond'), ('Purchase From SEZ - Nil Rated ', 'Purchase From SEZ - Nil Rated'), ('Purchase From SEZ - Taxable', 'Purchase From SEZ - Taxable'), ('Purchase From SEZ (Without Bill Of Entry) - Exempt', 'Purchase From SEZ (Without Bill Of Entry) - Exempt'), ('Purchase From SEZ (Without Bill Of Entry) - Nil Rated', 'Purchase From SEZ (Without Bill Of Entry) - Nil Rated'), ('Purchase From SEZ (Without Bill Of Entry) - Taxable', 'Purchase From SEZ (Without Bill Of Entry) - Taxable'), ('Purchase From Unregister Dealer - Exempt', 'Purchase From Unregister Dealer - Exempt'), ('Purchase From Unregister Dealer - Nil Rated', 'Purchase From Unregister Dealer - Nil Rated'), ('Purchase From Unregister Dealer - Taxable', 'Purchase From Unregister Dealer - Taxable'), ('Purchase Nil Rated', 'Purchase Nil Rated'), ('Intrastate Purchase Taxable', 'Intrastate Purchase Taxable')], default='Not Applicable', max_length=100),
        ),
    ]
