# Generated by Django 2.0.6 on 2019-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcategories',
            name='Title',
            field=models.CharField(default='Getting Started', max_length=255),
        ),
    ]
