# Generated by Django 2.0.6 on 2019-06-04 13:40

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcategories',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='help_image'),
        ),
    ]
