# Generated by Django 2.0.6 on 2019-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0002_auto_20190611_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='helpcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
