# Generated by Django 2.0.6 on 2019-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0004_remove_article_answers_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcategories',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
