# Generated by Django 2.0.6 on 2019-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0005_helpcategories_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcategories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
