# Generated by Django 2.0.6 on 2019-06-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpandsupport', '0006_helpcategories_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_answers',
            old_name='Questions',
            new_name='Question_of_article',
        ),
    ]
