# Generated by Django 2.0.6 on 2019-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tandc',
            field=models.BooleanField(default=True),
        ),
    ]
