# Generated by Django 2.0.6 on 2019-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190503_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
