# Generated by Django 2.0.6 on 2019-08-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import help_support.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ticket_type', models.CharField(blank=True, choices=[('Bugs', 'Bugs'), ('Complaint', 'Complaint'), ('Feedback', 'Feedback'), ('No Info', 'No Info'), ('Query', 'Query'), ('Request', 'Request'), ('Spam_ticket', 'Spam_ticket')], max_length=100)),
                ('file_upload', models.FileField(blank=True, upload_to='pro_verification', validators=[help_support.models.file_size, help_support.models.validate_file_extension])),
                ('status', models.CharField(choices=[('pending', 'pending for verification'), ('verified', 'verified'), ('approached', 'approached the user for further details'), ('in progress', 'in progress')], default='pending for verification', max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
