# Generated by Django 2.0.6 on 2019-08-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190821_1231'),
        ('CRMcommon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_Attachments', to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_Comment', to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment_files',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_Comment_Files', to='company.Company'),
            preserve_default=False,
        ),
    ]
