# Generated by Django 2.0.6 on 2019-09-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMcommon', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='account',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='case',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
    ]
