# Generated by Django 2.0.6 on 2019-08-24 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20190821_1231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_entry', '0006_auto_20190822_1716'),
        ('bracketline', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTaxAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_tax_ledger_accounts', to='accounting_entry.LedgerMaster')),
            ],
        ),
        migrations.CreateModel(
            name='SaleTermAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cess_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_term_ledger_accounts', to='accounting_entry.LedgerMaster')),
            ],
        ),
        migrations.CreateModel(
            name='SaleVoucherAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('url_hash', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100)),
                ('consignee_name', models.CharField(blank=True, default='Customer', max_length=200)),
                ('consignee_address', models.TextField(blank=True)),
                ('consignee_gstin', models.CharField(blank=True, max_length=15)),
                ('consignee_pan', models.CharField(blank=True, max_length=15)),
                ('consignee_contact', models.CharField(blank=True, max_length=15)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('other_details', models.CharField(blank=True, max_length=20, null=True)),
                ('nature_transactions_sales', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Branch Transfer outward', 'Branch Transfer outward'), ('Deemed Exports Exempt', 'Deemed Exports Exempt'), ('Deemed Exports Nil Rated', 'Deemed Exports Nil Rated'), ('Deemed Exports Taxable', 'Deemed Exports Taxable'), ('Exports Exempt', 'Exports Exempt'), ('Exports LUT/Bond', 'Exports LUT/Bond'), ('Exports Nil Rated', 'Exports Nil Rated'), ('Exports Taxable', 'Exports Taxable'), ('Interstate Sales Exempt', 'Interstate Sales Exempt'), ('Interstate Sales Nil Rated', 'Interstate Sales Nil Rated '), ('Interstate Sales - Taxable', 'Interstate Sales   - Taxable'), ('Interstate Sales to Embassy / UN Body Exempt', 'Interstate Sales to Embassy / UN Body Exempt'), ('Interstate Sales to Embassy / UN Body Nil Rated', 'Interstate Sales to Embassy / UN Body Nil Rated'), ('Interstate Sales to Embassy / UN Body Taxable', 'Interstate Sales to Embassy / UN Body Taxable'), ('Intrastate Deemed Exports Exempt', 'Intrastate Deemed Exports Exempt'), ('Intrastate Deemed Exports Nil Rated', 'Intrastate Deemed Exports Nil Rated'), ('Intrastate Deemed Exports Taxable', 'Intrastate Deemed Exports Taxable'), ('Sales Exempt', 'Sales Exempt'), ('Sales Nil Rated', 'Sales Nil Rated'), ('Intrastate Sales Taxable', 'Intrastate Sales Taxable'), ('Sales to Consumer - Exempt', 'Sales to Consumer - Exempt'), ('Sales to Consumer - Nil Rated', 'Sales to Consumer - Nil Rated'), ('Sales to Consumer - Taxable', 'Sales to Consumer - Taxable'), ('Sales to SEZ - Exempt', 'Sales to SEZ - Exempt'), ('Sales to SEZ - LUT/Bond', 'Sales to SEZ - LUT/Bond'), ('Sales to SEZ - Nil Rated', 'Sales to SEZ - Nil Rated'), ('Sales to SEZ - Taxable', 'Sales to SEZ - Taxable')], default='Not Applicable', max_length=100)),
                ('despatch_no', models.CharField(blank=True, max_length=132)),
                ('despatch_info', models.CharField(blank=True, max_length=132)),
                ('destination', models.CharField(blank=True, max_length=132)),
                ('landing_bill', models.CharField(blank=True, max_length=132)),
                ('landing_date', models.DateField(default=datetime.date.today)),
                ('vechicle_no', models.CharField(blank=True, max_length=132)),
                ('supplier_ref', models.CharField(blank=True, max_length=32)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cess_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gst_details', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('bill_no', models.CharField(blank=True, max_length=10)),
                ('bill_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('port_code', models.CharField(blank=True, max_length=10)),
                ('delivery_terms', models.TextField(blank=True)),
                ('shipper_place', models.TextField(blank=True)),
                ('flight_no', models.CharField(blank=True, max_length=20)),
                ('loading_port', models.CharField(blank=True, max_length=50)),
                ('discharge_port', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_sales_accounts', to='company.Company')),
                ('consignee_country', models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_consignee_country_accounts', to='bracketline.CountryMaster')),
                ('consignee_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_consignee_state_accounts', to='bracketline.StateMaster')),
                ('doc_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sale_ledger_accounts', to='accounting_entry.LedgerMaster')),
                ('party_ac', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_ledger_sales_accounts', to='accounting_entry.LedgerMaster')),
                ('supply_country', models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_supply_country_accounts', to='bracketline.CountryMaster')),
                ('supply_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_supply_state_accounts', to='bracketline.StateMaster')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saletermaccounts',
            name='sale_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_voucher_term_accounts', to='accounts_mode_voucher.SaleVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='saletaxaccounts',
            name='sale_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_voucher_tax_accounts', to='accounts_mode_voucher.SaleVoucherAccounts'),
        ),
    ]
