# Generated by Django 2.0.6 on 2019-08-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mode_voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salevoucheraccounts',
            name='doc_ledger',
        ),
    ]
