# Generated by Django 2.0.6 on 2019-09-09 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting_entry', '0002_auto_20190909_1940'),
        ('bracketline', '0001_initial'),
        ('accounts_mode_voucher', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_sales_accounts', to='company.Company'),
        ),
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='consignee_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_consignee_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='consignee_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_consignee_state_accounts', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='party_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_ledger_sales_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='supply_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_supply_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='supply_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_supply_state_accounts', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='salevoucheraccounts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saletermaccounts',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_term_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='saletermaccounts',
            name='sale_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_voucher_term_accounts', to='accounts_mode_voucher.SaleVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='saletaxaccounts',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_tax_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='saletaxaccounts',
            name='sale_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_voucher_tax_accounts', to='accounts_mode_voucher.SaleVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_purchase_accounts', to='company.Company'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='consignee_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_consignee_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='consignee_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_consignee_state_accounts', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='party_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_ledger_purchase_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='supply_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_supply_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='supply_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_supply_state_accounts', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='to_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_to_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='purchasevoucheraccounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasetermaccounts',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_term_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='purchasetermaccounts',
            name='purchase_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_voucher_term_accounts', to='accounts_mode_voucher.PurchaseVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='purchasetaxaccounts',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_tax_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='purchasetaxaccounts',
            name='purchase_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_voucher_tax_accounts', to='accounts_mode_voucher.PurchaseVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='debitnotetax',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_gst_accounts', to='accounts_mode_voucher.DebitNoteAccountsVoucher'),
        ),
        migrations.AddField(
            model_name='debitnotetax',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_note_tax_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_debit_note_accounts', to='company.Company'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsvoucher',
            name='party_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_ledger_debit_note_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsvoucher',
            name='purchase_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_purchase_voucher_accounts', to='accounts_mode_voucher.PurchaseVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsvoucher',
            name='supply_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_note_supply_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsvoucher',
            name='supply_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_note_supply_state_accounts', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsterm',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_extra_accounts', to='accounts_mode_voucher.DebitNoteAccountsVoucher'),
        ),
        migrations.AddField(
            model_name='debitnoteaccountsterm',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_note_term_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='creditnoteaccounttax',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_gst_accounts', to='accounts_mode_voucher.CreditNoteAccountsVoucher'),
        ),
        migrations.AddField(
            model_name='creditnoteaccounttax',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_note_tax_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_credit_note_accounts', to='company.Company'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsvoucher',
            name='party_ac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_ledger_credit_note_accounts', to='accounting_entry.LedgerMaster'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsvoucher',
            name='sale_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_note_sale_voucher_accounts', to='accounts_mode_voucher.SaleVoucherAccounts'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsvoucher',
            name='supply_country',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_note_supply_country_accounts', to='bracketline.CountryMaster'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsvoucher',
            name='supply_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_note_supply_state_accounts', to='bracketline.StateMaster'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsterm',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_term_accounts', to='accounts_mode_voucher.CreditNoteAccountsVoucher'),
        ),
        migrations.AddField(
            model_name='creditnoteaccountsterm',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_note_term_ledger_accounts', to='accounting_entry.LedgerMaster'),
        ),
    ]
