# Generated by Django 2.0.6 on 2019-09-09 14:10

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, default='user_profile/comming soon.jpg', null=True, upload_to='api_images')),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=4)),
                ('summary', models.TextField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashBackWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tran_desc', models.CharField(max_length=512)),
                ('tran_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tran_hash', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_from', models.DateField(default=datetime.date.today)),
                ('annual_inclusive_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('half_yearly_inclusive_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20)),
                ('quarterly_inclusive_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20)),
                ('monthly_inclusive_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('user_ref_disc_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('agent_ref_disc_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('image', models.ImageField(default='user_profile/comming soon.jpg', upload_to='product_images')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=4)),
                ('summary', models.TextField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, unique=True)),
                ('feature_summary', models.TextField(blank=True, max_length=255, null=True)),
                ('company_count', models.IntegerField(default=-1)),
                ('auditor_per_company', models.IntegerField(default=-1)),
                ('accountant_per_company', models.IntegerField(default=-1)),
                ('accountant_total', models.IntegerField(default=-1)),
                ('purchaser_per_company', models.IntegerField(default=-1)),
                ('seller_per_company', models.IntegerField(default=-1)),
                ('cashier_per_company', models.IntegerField(default=-1)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('suggested', models.BooleanField(default=False)),
                ('sorting_watage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('text', models.TextField()),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='ecommerce_integration.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('renewal_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('subscription_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], default='Yearly', max_length=20)),
                ('subscription_from', models.DateField(default=datetime.date.today)),
                ('subscription_upto', models.DateField(default=datetime.date.today)),
                ('month_count', models.PositiveIntegerField(default=0)),
                ('subscription_active', models.BooleanField(default=True)),
                ('price_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_subscription_price', to='ecommerce_integration.PriceModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleBasedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('image', models.ImageField(blank=True, default='user_profile/comming soon.jpg', null=True, upload_to='product_images')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=4)),
                ('summary', models.TextField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, default='user_profile/comming soon.jpg', null=True, upload_to='service_images')),
                ('summary', models.TextField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pricemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_base_price', to='ecommerce_integration.Product'),
        ),
        migrations.AddField(
            model_name='pricemodel',
            name='product_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_feature', to='ecommerce_integration.ProductFeature'),
        ),
        migrations.AlterUniqueTogether(
            name='pricemodel',
            unique_together={('product', 'apply_from', 'product_feature')},
        ),
    ]
