# Generated by Django 2.0.6 on 2019-09-09 14:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('act', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('form_type', models.CharField(choices=[('Agreement', 'Agreement'), ('Affidavit', 'Affidavit'), ('Form', 'Form')], default='Agreement', max_length=32)),
                ('category', models.CharField(choices=[('General', 'General'), ('Specific', 'Specific')], default='General', max_length=32)),
                ('textbody', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('guideline', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAggrements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('textbody', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('special_note', models.CharField(blank=True, max_length=100, null=True)),
                ('aggrement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_aggrement_control', to='aggrement.Aggrement')),
            ],
        ),
    ]
