# Generated by Django 2.0.6 on 2019-05-03 06:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_reconcilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=100)),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('ATM', 'ATM'), ('Cash', 'Cash'), ('Cheque/DD', 'Cheque/DD'), ('Card', 'Card'), ('ECS', 'ECS'), ('Electronic Cheque', 'Electronic Cheque'), ('Electronic DD/PO', 'Electronic DD/PO'), ('e-Fund Transfer', 'e-Fund Transfer'), ('Others', 'Others')], default='ATM', max_length=56)),
                ('instrument_no', models.IntegerField(blank=True, default=0)),
                ('bank_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamecontra', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='group1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('group_Name', models.CharField(max_length=32)),
                ('Nature_of_group1', models.CharField(choices=[('Assets', 'Assets'), ('Expenses', 'Expenses'), ('Income', 'Income'), ('Liabilities', 'Liabilities'), ('Not Applicable', 'Not Applicable')], default='Assets', max_length=32)),
                ('balance_nature', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Not Applicable', 'Not Applicable')], default='Debit', max_length=32)),
                ('Group_behaves_like_a_Sub_Group', models.BooleanField(default=False)),
                ('Nett_Debit_or_Credit_Balances_for_Reporting', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_group', to='company.company')),
                ('Master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_group', to='accounting_double_entry.group1')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=100)),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('narration', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ledger1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=32)),
                ('Opening_Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, null=True)),
                ('Balance_opening', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=100)),
                ('Address', models.TextField(blank=True)),
                ('State', models.CharField(blank=True, choices=[('Choose', 'Choose'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi '), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Choose', max_length=100)),
                ('Pin_Code', models.BigIntegerField(blank=True, null=True)),
                ('PanIt_No', models.CharField(blank=True, max_length=100)),
                ('GST_No', models.CharField(blank=True, max_length=100)),
                ('Closing_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companys', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ledger', to=settings.AUTH_USER_MODEL)),
                ('group1_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgergroups', to='accounting_double_entry.group1')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Multijournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('narration', models.TextField(blank=True)),
                ('By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgersmulti', to='accounting_double_entry.ledger1')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgersmulti', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Multijournaltotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Total_Debit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Total_Credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamemultijournaltotal', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Particularscontra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contras', to='accounting_double_entry.Contra')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particularcontra', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Particularspayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particularpayment', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Particularsreceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particularreceipt', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamepayment', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payledgers', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='Pl_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('voucher_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=100)),
                ('stock', models.CharField(blank=True, max_length=100, null=True)),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_expense', models.BooleanField(default=True)),
                ('it_head', models.CharField(choices=[('Salaries', 'Salaries'), ('Income_from_house_property', 'Income_from_house_property'), ('Profit_&_Gains_of_Business_and_Professions', 'Profit_&_Gains_of_Business_and_Professions'), ('Capital_Gains', 'Capital_Gains'), ('Income_from_other_sources', 'Income_from_other_sources')], default='Profit_&_Gains_of_Business_and_Professions', max_length=32)),
                ('By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgerspl', to='accounting_double_entry.ledger1')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamepl', to='company.company')),
                ('To', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgerspl', to='accounting_double_entry.ledger1')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamereceipt', to='company.company')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptledgers', to='accounting_double_entry.ledger1')),
            ],
        ),
        migrations.CreateModel(
            name='selectdatefield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('End_Date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='particularsreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounting_double_entry.Receipt'),
        ),
        migrations.AddField(
            model_name='particularspayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting_double_entry.Payment'),
        ),
        migrations.AddField(
            model_name='multijournal',
            name='total',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='accounting_double_entry.Multijournaltotal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgers', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companyname', to='company.company'),
        ),
        migrations.AddField(
            model_name='journal',
            name='To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgers', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='journal',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_journal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contra',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraledgers', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgersbank', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Companynamebank', to='company.company'),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgersbank', to='accounting_double_entry.ledger1'),
        ),
        migrations.AddField(
            model_name='bank_reconcilation',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
