# Generated by Django 2.0.6 on 2019-05-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0004_auto_20190506_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='Total_Credit',
        ),
        migrations.RemoveField(
            model_name='group1',
            name='Total_Debit',
        ),
        migrations.RemoveField(
            model_name='ledger1',
            name='Total_Credit',
        ),
        migrations.RemoveField(
            model_name='ledger1',
            name='Total_Debit',
        ),
    ]
