# Generated by Django 2.0.6 on 2019-05-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_composite_enable'),
        ('accounting_double_entry', '0008_auto_20190508_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='multijournal',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
