# Generated by Django 2.0.6 on 2019-05-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0009_multijournal_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multijournal',
            name='By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Debitledgersmulti', to='accounting_double_entry.ledger1'),
        ),
        migrations.AlterField(
            model_name='multijournal',
            name='Credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='multijournal',
            name='Debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='multijournal',
            name='To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creditledgersmulti', to='accounting_double_entry.ledger1'),
        ),
    ]
