# Generated by Django 2.0.6 on 2019-05-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0010_auto_20190513_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group1',
            name='Group_behaves_like_a_Sub_Group',
        ),
        migrations.RemoveField(
            model_name='group1',
            name='Nett_Debit_or_Credit_Balances_for_Reporting',
        ),
    ]
