# Generated by Django 2.0.6 on 2019-05-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0011_auto_20190514_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='group1',
            name='Group_behaves_like_a_Sub_Group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group1',
            name='Nett_Debit_or_Credit_Balances_for_Reporting',
            field=models.BooleanField(default=False),
        ),
    ]
