# Generated by Django 2.0.6 on 2019-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0012_auto_20190514_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multijournal',
            name='narration',
        ),
        migrations.AddField(
            model_name='multijournaltotal',
            name='narration',
            field=models.TextField(blank=True),
        ),
    ]
