# Generated by Django 2.0.6 on 2019-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0013_auto_20190521_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_journal',
            name='it_head',
            field=models.CharField(choices=[('Salaries', 'Salaries'), ('Income_from_house_property', 'Income_from_house_property'), ('Profit_&_Gains_of_Business_and_Professions', 'Profit_&_Gains_of_Business_and_Professions'), ('Capital_Gains', 'Capital_Gains'), ('Income_from_other_sources', 'Income_from_other_sources')], default='Profit_&_Gains_of_Business_and_Professions', max_length=100),
        ),
    ]
