# Generated by Django 2.0.6 on 2019-06-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0014_auto_20190527_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger1',
            name='To_pl_credit',
        ),
        migrations.RemoveField(
            model_name='ledger1',
            name='To_pl_debit',
        ),
    ]
