# Generated by Django 2.0.6 on 2019-06-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0017_auto_20190605_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger1',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
