# Generated by Django 2.0.6 on 2019-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0018_ledger1_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='voucher_type',
            field=models.CharField(blank=True, default='Journal', max_length=100),
        ),
    ]
