# Generated by Django 2.0.6 on 2019-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_double_entry', '0019_auto_20190610_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group1',
            name='negative_closing',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='group1',
            name='negative_opening',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='group1',
            name='positive_closing',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='group1',
            name='positive_opening',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True),
        ),
    ]
