# Generated by Django 2.0.6 on 2019-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(related_name='lead_contacts', to='CRM.Contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, to='CRM.Tags'),
        ),
    ]
