# Generated by Django 2.0.6 on 2019-08-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190821_1231'),
        ('CRM', '0003_event_task_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_Event', to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_Tasks', to='company.Company'),
            preserve_default=False,
        ),
    ]
