# Generated by Django 2.0.6 on 2019-09-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20190912_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
    ]
