# Generated by Django 2.0.6 on 2019-05-03 06:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('urlhash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('Name', models.CharField(max_length=50)),
                ('bussiness_nature', models.CharField(choices=[('Service Provider', 'Service Provider'), ('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Works Contract', 'Works Contract'), ('Leasing', 'Leasing'), ('Factory Manufacturing', 'Factory Manufacturing'), ('Bonded Warehouse', 'Bonded Warehouse')], default='Retail', max_length=32)),
                ('maintain', models.CharField(choices=[('Accounts Only', 'Accounts Only'), ('Accounts with Inventory', 'Accounts with Inventory')], default='Accounts with Inventory', max_length=32)),
                ('Type_of_company', models.CharField(choices=[('Individual', 'Individual'), ('HUF', 'HUF'), ('Partnership', 'Partnership'), ('Trust', 'Trust'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('LLP', 'LLP')], default='Individual', max_length=32)),
                ('Address', models.TextField()),
                ('Country', models.CharField(default='India', max_length=32)),
                ('State', models.CharField(choices=[('Choose', 'Choose'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi '), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Choose', max_length=100)),
                ('Pincode', models.CharField(max_length=32)),
                ('Telephone_No', models.BigIntegerField(blank=True, null=True)),
                ('Mobile_No', models.BigIntegerField(blank=True, null=True)),
                ('Financial_Year_From', models.DateField(choices=[(datetime.date(2019, 4, 1), datetime.date(2019, 4, 1)), (datetime.date(2019, 1, 1), datetime.date(2019, 1, 1))], default=datetime.date(2019, 4, 1), max_length=100)),
                ('Books_Begining_From', models.DateField(default=datetime.date(2018, 4, 1))),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('pan', models.CharField(blank=True, max_length=18, null=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Owner', to=settings.AUTH_USER_MODEL)),
                ('accountant', models.ManyToManyField(blank=True, related_name='main_accountant', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ManyToManyField(blank=True, related_name='main_auditor', to=settings.AUTH_USER_MODEL)),
                ('cb_personal', models.ManyToManyField(blank=True, related_name='main_cb', to=settings.AUTH_USER_MODEL)),
                ('purchase_personal', models.ManyToManyField(blank=True, related_name='main_purchase', to=settings.AUTH_USER_MODEL)),
                ('sales_personal', models.ManyToManyField(blank=True, related_name='main_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
