# Generated by Django 2.0.6 on 2019-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='asset',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
