# Generated by Django 2.0.6 on 2019-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190508_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='asset',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
