# Generated by Django 2.0.6 on 2019-08-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190820_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='organisation/cover'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organisation/logo'),
        ),
    ]
