# Generated by Django 2.0.6 on 2019-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190508_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
