# Generated by Django 2.0.6 on 2019-05-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190508_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='composite_enable',
            field=models.BooleanField(default=False),
        ),
    ]
