# Generated by Django 2.0.6 on 2019-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_composite_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Financial_Year_From',
            field=models.CharField(choices=[('1st:April-31st:March', '1st:April-31st:March'), ('1st:Jan-31st:December', '1st:Jan-31st:December')], default='1st:April-31st:March', max_length=100),
        ),
    ]
