# Generated by Django 2.0.6 on 2019-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190514_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='urlhash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
