# Generated by Django 2.0.6 on 2019-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20190520_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='purchase_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
