# Generated by Django 2.0.6 on 2019-06-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20190610_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='purchase_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sales_enabled',
        ),
    ]
