# Generated by Django 2.0.6 on 2019-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20190610_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
