# Generated by Django 2.0.6 on 2019-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_enable_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_sales',
            field=models.BooleanField(default=False),
        ),
    ]
