# Generated by Django 2.0.6 on 2019-09-09 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce_integration', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('wallet_balance_apply', models.BooleanField(default=True)),
                ('referral_code', models.CharField(blank=True, max_length=15, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_order_amount', models.PositiveIntegerField(default=0)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('razorpay_attempts', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_referrer', to='user_profile.Profile')),
                ('wallet_tran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_tran_applied', to='ecommerce_integration.CashBackWallet')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_count', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('renewal_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ref_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='ecommerce_cart.Order')),
                ('price_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_integration.PriceModel')),
            ],
        ),
    ]
