# Generated by Django 2.0.6 on 2019-05-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('stockkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_total_sales',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
