# Generated by Django 2.0.6 on 2019-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0002_stock_total_sales_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_total',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stock_total_sales',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
