# Generated by Django 2.0.6 on 2019-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0003_auto_20190509_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_alltotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax_alltotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
