# Generated by Django 2.0.6 on 2019-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0004_auto_20190509_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_total',
            name='tax_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock_total_sales',
            name='tax_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
