# Generated by Django 2.0.6 on 2019-05-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0005_auto_20190509_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_journal',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_stock_journal', to='company.company'),
        ),
    ]
