# Generated by Django 2.0.6 on 2019-05-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0006_auto_20190510_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companypurchase', to='company.company'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companysales', to='company.company'),
        ),
    ]
