# Generated by Django 2.0.6 on 2019-05-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0007_auto_20190511_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_stock', to='company.company'),
        ),
    ]
