# Generated by Django 2.0.6 on 2019-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0008_auto_20190511_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
