# Generated by Django 2.0.6 on 2019-05-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0009_auto_20190514_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Address',
            field=models.TextField(blank=True),
        ),
    ]
