# Generated by Django 2.0.6 on 2019-05-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20190520_1251'),
        ('stockkeeping', '0010_auto_20190514_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('Company', 'stock_name')},
        ),
    ]
