# Generated by Django 2.0.6 on 2019-05-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeping', '0011_auto_20190524_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set(),
        ),
    ]
