# Generated by Django 2.0.6 on 2019-05-29 09:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('bare_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('facts', models.TextField(blank=True, max_length=100, null=True)),
                ('issues', models.TextField(blank=True, max_length=100, null=True)),
                ('ratio', models.TextField(blank=True, max_length=100, null=True)),
                ('arguments', models.TextField(blank=True, max_length=100, null=True)),
                ('judgement', models.TextField(blank=True, max_length=100, null=True)),
                ('critics', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Forex & Banking', 'Forex & Banking'), ('Capital Market', 'Capital Market'), ('Corporate Laws', 'Corporate Laws'), ('Competition Laws', 'Competition Laws'), ('Indirect Taxation', 'Indirect Taxation'), ('Direct Taxation', 'Direct Taxation'), ('VAT', 'VAT'), ('Sales Tax', 'Sales Tax'), ('Compliance Almanac', 'Compliance Almanac'), ('Employment Laws', 'Employment Laws'), ('Labour', 'Labour'), ('Insurance', 'Insurance'), ('Industrial & Service', 'Industrial & Service'), ('Human Rights', 'Human Rights'), ('Foreign Trade Policy', 'Foreign Trade Policy'), ('Indian Industrial Policy', 'Indian Industrial Policy'), ('Environment', 'Environment'), ('Intellectual Property Rights', 'Intellectual Property Rights'), ('Cyber & IT Laws', 'Cyber & IT Laws'), ('Media & Communication', 'Media & Communication'), ('Anti-Dumping', 'Anti-Dumping'), ('WTO', 'WTO'), ('Power & Energy', 'Power & Energy'), ('Mines & Minerals', 'Mines & Minerals')], default='Forex & Banking', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Central_bare_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('bare_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('cases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_acts_cases', to='legal_database.Cases')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_acts', to='legal_database.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('central_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_acts_chap', to='legal_database.Central_bare_act')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('central_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_acts_sec', to='legal_database.Central_bare_act')),
            ],
        ),
        migrations.CreateModel(
            name='State_bare_act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('bare_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('cases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_acts_cases', to='legal_database.Cases')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sb_acts', to='legal_database.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal_database.Section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='state_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_acts_sec', to='legal_database.State_bare_act'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='state_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_acts_chap', to='legal_database.State_bare_act'),
        ),
    ]
