# Generated by Django 2.0.6 on 2019-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0003_cases_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='sitations',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='sitations',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sub_section',
            name='sitations',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
