# Generated by Django 2.0.6 on 2019-05-29 13:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0004_auto_20190529_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sitations', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sitations', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Case_cat', to='legal_database.Categories'),
        ),
        migrations.AddField(
            model_name='order',
            name='cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cases', to='legal_database.Cases'),
        ),
        migrations.AddField(
            model_name='order',
            name='central_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_acts_order', to='legal_database.Central_bare_act'),
        ),
        migrations.AddField(
            model_name='order',
            name='state_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_acts_order', to='legal_database.State_bare_act'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_cases', to='legal_database.Cases'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='central_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb_acts_noti', to='legal_database.Central_bare_act'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='state_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_acts_noti', to='legal_database.State_bare_act'),
        ),
    ]
