# Generated by Django 2.0.6 on 2019-05-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0005_auto_20190529_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_category', to='legal_database.Categories'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_category', to='legal_database.Categories'),
        ),
    ]
