# Generated by Django 2.0.6 on 2019-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0006_auto_20190529_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='arguments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='critics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='judgement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='ratio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='sitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='central_bare_act',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state_bare_act',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_section',
            name='sitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_section',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
