# Generated by Django 2.0.6 on 2019-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0007_auto_20190531_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
