# Generated by Django 2.0.6 on 2019-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0008_section_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
