# Generated by Django 2.0.6 on 2019-05-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0009_section_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='sitations',
            new_name='citations',
        ),
    ]
