# Generated by Django 2.0.6 on 2019-05-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0010_auto_20190531_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='counter',
        ),
    ]
