# Generated by Django 2.0.6 on 2019-06-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0011_remove_section_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('Forex & Banking', 'Forex & Banking'), ('Capital Market', 'Capital Market'), ('Corporate Laws', 'Corporate Laws'), ('Competition Laws', 'Competition Laws'), ('Indirect Taxation', 'Indirect Taxation'), ('Direct Taxation', 'Direct Taxation'), ('VAT', 'VAT'), ('Sales Tax', 'Sales Tax'), ('Compliance Almanac', 'Compliance Almanac'), ('Employment Laws', 'Employment Laws'), ('Labour', 'Labour'), ('Criminal Laws', 'Criminal Laws'), ('Insurance', 'Insurance'), ('Industrial & Service', 'Industrial & Service'), ('Human Rights', 'Human Rights'), ('Foreign Trade Policy', 'Foreign Trade Policy'), ('Indian Industrial Policy', 'Indian Industrial Policy'), ('Environment', 'Environment'), ('Intellectual Property Rights', 'Intellectual Property Rights'), ('Cyber & IT Laws', 'Cyber & IT Laws'), ('Media & Communication', 'Media & Communication'), ('Anti-Dumping', 'Anti-Dumping'), ('WTO', 'WTO'), ('Power & Energy', 'Power & Energy'), ('Mines & Minerals', 'Mines & Minerals')], default='Forex & Banking', max_length=32, unique=True),
        ),
    ]
