# Generated by Django 2.0.6 on 2019-06-05 08:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_database', '0012_auto_20190604_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='citations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_section',
            name='sitations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
