# Generated by Django 2.0.6 on 2019-09-09 14:10

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bracketline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_pic')),
                ('job_title', models.CharField(max_length=50)),
                ('location', models.TextField(blank=True, null=True)),
                ('job_function', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Permanent', 'Permanent'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Part-time', 'Part-time')], default='Choose', max_length=100)),
                ('company_industry', models.CharField(max_length=50)),
                ('seniority', models.CharField(blank=True, choices=[('Entry level', 'Entry level'), ('Associate', 'Associate'), ('Internship', 'Internship'), ('Mid-senior-level', 'Mid-senior-level'), ('Director', 'Director'), ('Executive', 'Executive'), ('Not Available', 'Not Available')], default='Choose', max_length=100, null=True)),
                ('job_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company_organisation', to='company.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_owner_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cv_pic')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=32)),
                ('mobile_no', models.CharField(max_length=32)),
                ('degree', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=100)),
                ('marks', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('time_period_from', models.DateField(blank=True, null=True)),
                ('time_period_to', models.DateField(blank=True, null=True)),
                ('working_experince', models.BooleanField(default=False)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('company_city', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_from', models.DateField(blank=True, null=True)),
                ('experience_to', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('desired_job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('desired_job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Permanent', 'Permanent'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Part-time', 'Part-time')], default='Choose', max_length=100)),
                ('desired_salary', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resume_state', to='bracketline.StateMaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_owner_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
